### ISSUE TITLE
Possible additions?

### ISSUE THREAD

**Issue by grandamp** [pkic/pqccm#11]
- IBM [CCA](https://www.ibm.com/security/cryptocards/pciecc4/cca) & [EP11](https://www.ibm.com/docs/en/linux-on-systems?topic=token-quantum-safe-cryptography) support for Dilithium
- Amazon Web Services [KMS](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration-crt.html#post-quantum-tls-support)  support for Kyber

**Comment by primetomas** [comment]
KMS does not offer any capabilities for a user to play with, only TLS connection to the AWS infrastructure, do I understand it correctly? We didn't specify any specific use for the pqccm so I guess it complies though. 
CCA and EP11 clearly lists the algorithm (round 2 only though), so definitely. 
Do you want to make a PR or should I add it in?

**Comment by primetomas** [comment]
Added IBM. Did not add AWS TLS support, but added a clarification to the PQCCM that the product in question (KMS in this case) should offer some PQC functionality to the end user, not merely access.

**Comment by grandamp** [comment]
Thanks @primetomas !

Apologies for the delay...

I was not certain if pull requests were limited to vendors, and didn't want to be awkward :)
