### ISSUE TITLE
updated README with ISC products

### ISSUE THREAD

**Issue by markowitz-isc** [pkic/pqccm#18]
added 2 products to the table and short company description; made a few grammar corrections; not sure if i have permission to create pull requests, so i'm entering this as an issue; not yet a member, but submitted application on Friday.  thanks!  -- markowitz
[README.MD](https://github.com/pkic/pqccm/files/10889849/README.MD)

**Comment by vanbroup** [comment]
Thanks It would be great if you could create a pull request!

**Comment by markowitz-isc** [comment]
Hi, Paul.   Not exactly sure that you want me to create a pull request... I can't create a branch and pushes to the main branch are blocked.

Github newbie!   ???

-mjm

**Comment by vanbroup** [comment]
Closed by #19
