### ISSUE TITLE
Add new vendor to the PQC Capabilities Matrix 

### ISSUE THREAD

**Issue by PrescilliaL** [pkic/pqccm#44]
Hello, 

Could you please add this company to the PQC Capabilities Matrix, here the details : 

For the table : 

| [Eviden](#eviden)                     | Trustway Proteccio™ NetHSM          | HSM              | 20242-12-09  |          :heavy_check_mark:           |          :heavy_check_mark:           |         :x:         |         :x:         |         :x:         |   :heavy_check_mark:    |         :x:         |   :heavy_check_mark:    |         :x:         |         :x:         |         :x:         |

For the summary : 

## Eviden 
**Trustway Proteccio™ NetHSM**

The [Eviden Trustway Proteccio™ NetHSM](https://eviden.com/solutions/digital-security/data-encryption/trustway-proteccio-nethsm/) supports all common cryptographic algorithms including the PQC algorithms selected by NIST : CRYSTALS-Kyber and CRYSTALS-Dilithium. 

Thank you,

**Comment by primetomas** [comment]
Are you able to make a pull request? That will make it trivial for us to add it.

**Comment by PrescilliaL** [comment]
I've never done it, but I will try ! Thanks

**Comment by PrescilliaL** [comment]
I can not create a pull request, I get this message : "Pull request creation failed. Validation failed: must be a collaborator"

**Comment by primetomas** [comment]
Should be able to create a PR, from a forked repo. To create a pull request, you have to:
- fork the project into your personal repository
- create a new branch in your own (forked) repo
- after making changes to your repo, there should appear a button to "create PR"

**Comment by PrescilliaL** [comment]
Ok thanks, I think it worked

**Comment by primetomas** [comment]
It should have showed up here then, but it's not there: https://github.com/pkic/pqccm/pulls

**Comment by PrescilliaL** [comment]
Now you should see it

**Comment by primetomas** [comment]
Yes, thanks. I will review and merge it.

**Comment by primetomas** [comment]
Merged. But I saw that you have checked Composite and Hybrid certificates. Is that correct for an HSM?

**Comment by PrescilliaL** [comment]
Indeed, I need to make the change sorry for that.
